class PacketSize:
    DATA_SEGMENT = 512
    SENDER_MASTER_TO_SLAVE = 256
    SENDER_SLAVE_TO_MASTER = 256
    RECEIVER_MASTER_TO_SLAVE = 256
    RECEIVER_SLAVE_TO_MASTER = 256
    SENDER_MASTER_TO_RECEIVER = 256
    RECEIVER_MASTER_TO_SENDER = 256
    SENDER_SLAVE_TO_RECEIVER = 1024

class PacketType:
    SYN = 0
    SYN_ACK = 1
    SYN_ACK_RECEIVED = 3
    FIN = 4
    FIN_ACK = 5
    FIN_ACK_RECEIVED = 6
    ASSIGN = 7
    ASSIGN_ACK = 8
    RECEIVER_ADDRESSES = 9
    RECEIVER_ADDRESSES_ACK = 10
    PACKET_RECEIVED = 11
    PACKET_RECEIVED_ACK = 12
    DATA = 13
    ACK = 14
    